(function () {
    'use strict';

    angular
        .module('g1mApp')
        .factory('addressFactory', address_factory);

    address_factory.$inject = [];

    function address_factory() {

        var service = {
            initializeAddress: initializeAddress,
            getUsStates: getUsStates,
            getCountries: getCountries,
        };

        return service;

        function initializeAddress() {
            return {
                address1: '',
                address2: '',
                city: '',
                state: '',
                zip: '',
                country: '',
                phone: ''
            };
        }

        function getUsStates() {
            return [
                { id: 'AL', name: 'Alabama' },
                { id: 'AK', name: 'Alaska' },
                { id: 'AZ', name: 'Arizona' },
                { id: 'AR', name: 'Arkansas' },
                { id: 'CA', name: 'California' },
                { id: 'CO', name: 'Colorado' },
                { id: 'CT', name: 'Connecticut' },
                { id: 'DE', name: 'Delaware' },
                { id: 'FL', name: 'Florida' },
                { id: 'GA', name: 'Georgia' },
                { id: 'HI', name: 'Hawaii' },
                { id: 'ID', name: 'Idaho' },
                { id: 'IL', name: 'Illinois' },
                { id: 'IN', name: 'Indiana' },
                { id: 'IA', name: 'Iowa' },
                { id: 'KS', name: 'Kansas' },
                { id: 'KY', name: 'Kentucky' },
                { id: 'LA', name: 'Louisiana' },
                { id: 'ME', name: 'Maine' },
                { id: 'MD', name: 'Maryland' },
                { id: 'MA', name: 'Massachusetts' },
                { id: 'MI', name: 'Michigan' },
                { id: 'MN', name: 'Minnesota' },
                { id: 'MS', name: 'Mississippi' },
                { id: 'MO', name: 'Missouri' },
                { id: 'MT', name: 'Montana' },
                { id: 'NE', name: 'Nebraska' },
                { id: 'NV', name: 'Nevada' },
                { id: 'NH', name: 'New Hampshire' },
                { id: 'NJ', name: 'New Jersey' },
                { id: 'NM', name: 'New Mexico' },
                { id: 'NY', name: 'New York' },
                { id: 'NC', name: 'North Carolina' },
                { id: 'ND', name: 'North Dakota' },
                { id: 'OH', name: 'Ohio' },
                { id: 'OK', name: 'Oklahoma' },
                { id: 'OR', name: 'Oregon' },
                { id: 'PA', name: 'Pennsylvania' },
                { id: 'RI', name: 'Rhode Island' },
                { id: 'SC', name: 'South Carolina' },
                { id: 'SD', name: 'South Dakota' },
                { id: 'TN', name: 'Tennessee' },
                { id: 'TX', name: 'Texas' },
                { id: 'UT', name: 'Utah' },
                { id: 'VT', name: 'Vermont' },
                { id: 'VA', name: 'Virginia' },
                { id: 'WA', name: 'Washington' },
                { id: 'WV', name: 'West Virginia' },
                { id: 'WI', name: 'Wisconsin' },
                { id: 'WY', name: 'Wyoming' }
            ];
        }

        function getCountries() {
            var countries = [
                // BL - { isoCode: 'AF', name: 'Afghanistan' },
                { isoCode: 'AX', name: 'Åland Islands' },
                { isoCode: 'AL', name: 'Albania' },
                { isoCode: 'DZ', name: 'Algeria' },
                { isoCode: 'AS', name: 'American Samoa' },
                { isoCode: 'AD', name: 'Andorra' },
                { isoCode: 'AO', name: 'Angola' },
                { isoCode: 'AI', name: 'Anguilla' },
                { isoCode: 'AG', name: 'Antigua & Barbuda' },
                { isoCode: 'AR', name: 'Argentina' },
                { isoCode: 'AM', name: 'Armenia' },
                { isoCode: 'AW', name: 'Aruba' },
                { isoCode: 'AU', name: 'Australia' },
                { isoCode: 'AT', name: 'Austria' },
                // BL - { isoCode: 'AZ', name: 'Azerbaijan' },
                { isoCode: 'BS', name: 'Bahamas' },
                { isoCode: 'BH', name: 'Bahrain' },
                { isoCode: 'BD', name: 'Bangladesh' },
                { isoCode: 'BB', name: 'Barbados' },
                // BL - { isoCode: 'BY', name: 'Belarus' },
                { isoCode: 'BE', name: 'Belgium' },
                { isoCode: 'BZ', name: 'Belize' },
                { isoCode: 'BJ', name: 'Benin' },
                { isoCode: 'BM', name: 'Bermuda' },
                { isoCode: 'BT', name: 'Bhutan' },
                { isoCode: 'BO', name: 'Bolivia' },
                { isoCode: 'BQ', name: 'Bonaire, Sint Eustatius, and Saba' },
                { isoCode: 'BA', name: 'Bosnia-Herzegovina' },
                { isoCode: 'BW', name: 'Botswana' },
                { isoCode: 'BV', name: 'Bouvet Island' },
                { isoCode: 'BR', name: 'Brazil' },
                { isoCode: 'IO', name: 'British Indian Ocean Territory' },
                { isoCode: 'BN', name: 'Brunei' },
                { isoCode: 'BG', name: 'Bulgaria' },
                { isoCode: 'BF', name: 'Burkina Faso' },
                { isoCode: 'BI', name: 'Burundi' },
                { isoCode: 'KH', name: 'Cambodia' },
                { isoCode: 'CM', name: 'Cameroon' },
                { isoCode: 'CA', name: 'Canada' },
                { isoCode: 'CV', name: 'Cape Verde' },
                { isoCode: 'KY', name: 'Cayman Islands' },
                { isoCode: 'CF', name: 'Central African Republic' },
                { isoCode: 'TD', name: 'Chad' },
                { isoCode: 'CL', name: 'Chile' },
                // BL - { isoCode: 'CN', name: 'China' },
                { isoCode: 'CX', name: 'Christmas Island' },
                { isoCode: 'CC', name: 'Cocos (Keeling) Islands' },
                { isoCode: 'CO', name: 'Colombia' },
                { isoCode: 'KM', name: 'Comoros' },
                { isoCode: 'CG', name: 'Congo-Brazzaville' },
                { isoCode: 'CD', name: 'Congo, The Democratic Republic of the' },
                { isoCode: 'CK', name: 'Cook Islands' },
                { isoCode: 'CR', name: 'Costa Rica' },
                { isoCode: 'CI', name: 'Côte d\'Ivoire' },
                { isoCode: 'HR', name: 'Croatia' },
                // BL - { isoCode: 'CU', name: 'Cuba' },
                { isoCode: 'CW', name: 'Curaçao' },
                { isoCode: 'CY', name: 'Cyprus' },
                // BL - { isoCode: 'CZ', name: 'Czech Republic' },
                { isoCode: 'DK', name: 'Denmark' },
                { isoCode: 'DJ', name: 'Djibouti' },
                { isoCode: 'DM', name: 'Dominica' },
                { isoCode: 'DO', name: 'Dominican Republic' },
                { isoCode: 'EC', name: 'Ecuador' },
                { isoCode: 'EG', name: 'Egypt' },
                { isoCode: 'SV', name: 'El Salvador' },
                { isoCode: 'GQ', name: 'Equatorial Guinea' },
                { isoCode: 'ER', name: 'Eritrea' },
                { isoCode: 'EE', name: 'Estonia' },
                // BL - { isoCode: 'ET', name: 'Ethiopia' },
                { isoCode: 'FK', name: 'Falkland Islands' },
                { isoCode: 'FO', name: 'Faroe Islands' },
                { isoCode: 'FJ', name: 'Fiji' },
                { isoCode: 'FI', name: 'Finland' },
                { isoCode: 'FR', name: 'France' },
                { isoCode: 'GF', name: 'French Guiana' },
                { isoCode: 'PF', name: 'French Polynesia' },
                { isoCode: 'TF', name: 'French Southern Territories' },
                { isoCode: 'GA', name: 'Gabon' },
                { isoCode: 'GM', name: 'Gambia' },
                { isoCode: 'GE', name: 'Georgia' },
                { isoCode: 'DE', name: 'Germany' },
                // BL - { isoCode: 'GH', name: 'Ghana' },
                { isoCode: 'GI', name: 'Gibraltar' },
                { isoCode: 'GR', name: 'Greece' },
                { isoCode: 'GL', name: 'Greenland' },
                { isoCode: 'GD', name: 'Grenada' },
                { isoCode: 'GP', name: 'Guadeloupe' },
                { isoCode: 'GU', name: 'Guam' },
                { isoCode: 'GT', name: 'Guatemala' },
                { isoCode: 'GG', name: 'Guernsey' },
                { isoCode: 'GN', name: 'Guinea' },
                { isoCode: 'GW', name: 'Guinea-Bissau' },
                { isoCode: 'GY', name: 'Guyana' },
                // BL - { isoCode: 'HT', name: 'Haiti' },
                { isoCode: 'HM', name: 'Heard Island and the McDonald Islands' },
                { isoCode: 'HN', name: 'Honduras' },
                { isoCode: 'HK', name: 'Hong Kong' },
                { isoCode: 'HU', name: 'Hungary' },
                { isoCode: 'IS', name: 'Iceland' },
                { isoCode: 'IN', name: 'India' },
                { isoCode: 'ID', name: 'Indonesia' },
                // BL - { isoCode: 'IR', name: 'Iran' },
                // BL - { isoCode: 'IQ', name: 'Iraq' },
                { isoCode: 'IE', name: 'Ireland' },
                { isoCode: 'IM', name: 'Isle of Man' },
                { isoCode: 'IL', name: 'Israel' },
                { isoCode: 'IT', name: 'Italy' },
                { isoCode: 'JM', name: 'Jamaica' },
                { isoCode: 'JP', name: 'Japan' },
                { isoCode: 'JE', name: 'Jersey' },
                { isoCode: 'JO', name: 'Jordan' },
                { isoCode: 'KZ', name: 'Kazakhstan' },
                { isoCode: 'KE', name: 'Kenya' },
                { isoCode: 'KI', name: 'Kiribati' },
                // BL - { isoCode: 'KR', name: 'Korea, Republic of' },
                { isoCode: 'KW', name: 'Kuwait' },
                { isoCode: 'KG', name: 'Kyrgyzstan' },
                { isoCode: 'LA', name: 'Lao People\'s Democratic Republic' },
                { isoCode: 'LV', name: 'Latvia' },
                { isoCode: 'LB', name: 'Lebanon' },
                { isoCode: 'LS', name: 'Lesotho' },
                { isoCode: 'LR', name: 'Liberia' },
                { isoCode: 'LY', name: 'Libya' },
                { isoCode: 'LI', name: 'Liechtenstein' },
                { isoCode: 'LT', name: 'Lithuania' },
                { isoCode: 'LU', name: 'Luxembourg' },
                { isoCode: 'MO', name: 'Macau' },
                { isoCode: 'MK', name: 'Macedonia' },
                { isoCode: 'MG', name: 'Madagascar' },
                { isoCode: 'MW', name: 'Malawi' },
                { isoCode: 'MY', name: 'Malaysia' },
                { isoCode: 'MV', name: 'Maldives' },
                { isoCode: 'ML', name: 'Mali' },
                { isoCode: 'MT', name: 'Malta' },
                { isoCode: 'MH', name: 'Marshall Islands' },
                { isoCode: 'MQ', name: 'Martinique' },
                { isoCode: 'MR', name: 'Mauritania' },
                { isoCode: 'MU', name: 'Mauritius' },
                { isoCode: 'YT', name: 'Mayotte' },
                { isoCode: 'MX', name: 'Mexico' },
                { isoCode: 'FM', name: 'Micronesia, Federated States of' },
                { isoCode: 'MD', name: 'Moldova, Republic of' },
                { isoCode: 'MC', name: 'Monaco' },
                { isoCode: 'MN', name: 'Mongolia' },
                { isoCode: 'ME', name: 'Montenegro' },
                { isoCode: 'MS', name: 'Montserrat' },
                { isoCode: 'MA', name: 'Morocco' },
                { isoCode: 'MZ', name: 'Mozambique' },
                { isoCode: 'MM', name: 'Myanmar' },
                { isoCode: 'NA', name: 'Namibia' },
                { isoCode: 'NR', name: 'Nauru' },
                { isoCode: 'NP', name: 'Nepal' },
                { isoCode: 'NL', name: 'Netherlands' },
                { isoCode: 'NC', name: 'New Caledonia' },
                { isoCode: 'NZ', name: 'New Zealand' },
                { isoCode: 'NI', name: 'Nicaragua' },
                { isoCode: 'NE', name: 'Niger' },
                { isoCode: 'NG', name: 'Nigeria' },
                { isoCode: 'NU', name: 'Niue' },
                { isoCode: 'NF', name: 'Norfolk Island' },
                { isoCode: 'MP', name: 'Northern Mariana Islands' },
                { isoCode: 'NO', name: 'Norway' },
                { isoCode: 'OM', name: 'Oman' },
                { isoCode: 'PK', name: 'Pakistan' },
                { isoCode: 'PW', name: 'Palau' },
                { isoCode: 'PS', name: 'Palestinian Territories' },
                { isoCode: 'PA', name: 'Panama' },
                { isoCode: 'PG', name: 'Papua New Guinea' },
                { isoCode: 'PY', name: 'Paraguay' },
                { isoCode: 'PE', name: 'Peru' },
                { isoCode: 'PH', name: 'Philippines' },
                { isoCode: 'PN', name: 'Pitcairn Islands' },
                // BL - { isoCode: 'PL', name: 'Poland' },
                { isoCode: 'PT', name: 'Portugal' },
                { isoCode: 'PR', name: 'Puerto Rico' },
                { isoCode: 'QA', name: 'Qatar' },
                { isoCode: 'RE', name: 'Réunion' },
                // BL - { isoCode: 'RO', name: 'Romania' },
                // BL - { isoCode: 'RU', name: 'Russia' },
                { isoCode: 'RW', name: 'Rwanda' },
                { isoCode: 'BL', name: 'Saint Barthélemy' },
                { isoCode: 'SH', name: 'Saint Helena' },
                { isoCode: 'KN', name: 'Saint Kitts and Nevis' },
                { isoCode: 'LC', name: 'Saint Lucia' },
                { isoCode: 'MF', name: 'Saint Martin' },
                { isoCode: 'PM', name: 'Saint Pierre & Miquelon' },
                { isoCode: 'VC', name: 'Saint Vincent and the Grenadines' },
                { isoCode: 'WS', name: 'Samoa' },
                { isoCode: 'SM', name: 'San Marino' },
                { isoCode: 'ST', name: 'São Tomé & Príncipe' },
                { isoCode: 'SA', name: 'Saudi Arabia' },
                { isoCode: 'SN', name: 'Senegal' },
                { isoCode: 'RS', name: 'Serbia' },
                { isoCode: 'SC', name: 'Seychelles' },
                { isoCode: 'SL', name: 'Sierra Leone' },
                { isoCode: 'SG', name: 'Singapore' },
                { isoCode: 'SX', name: 'Sint Maarten' },
                { isoCode: 'SK', name: 'Slovakia' },
                { isoCode: 'SI', name: 'Slovenia' },
                { isoCode: 'SB', name: 'Solomon Islands' },
                // BL - { isoCode: 'SO', name: 'Somalia' },
                { isoCode: 'ZA', name: 'South Africa' },
                { isoCode: 'GS', name: 'South Georgia and Sandwich' },
                // BL - { isoCode: 'SS', name: 'South Sudan' },
                { isoCode: 'ES', name: 'Spain' },
                { isoCode: 'LK', name: 'Sri Lanka' },
                // BL - { isoCode: 'SD', name: 'Sudan' },
                { isoCode: 'SR', name: 'Suriname' },
                { isoCode: 'SJ', name: 'Svalbard and Jan Mayen' },
                { isoCode: 'SZ', name: 'Swaziland' },
                { isoCode: 'SE', name: 'Sweden' },
                { isoCode: 'CH', name: 'Switzerland' },
                // BL - { isoCode: 'SY', name: 'Syria' },
                { isoCode: 'TW', name: 'Taiwan' },
                { isoCode: 'TJ', name: 'Tajikistan' },
                { isoCode: 'TZ', name: 'Tanzania' },
                { isoCode: 'TH', name: 'Thailand' },
                { isoCode: 'TL', name: 'Timor-Leste' },
                { isoCode: 'TG', name: 'Togo' },
                { isoCode: 'TK', name: 'Tokelau' },
                { isoCode: 'TO', name: 'Tonga' },
                { isoCode: 'TT', name: 'Trinidad & Tobago' },
                { isoCode: 'TN', name: 'Tunisia' },
                { isoCode: 'TR', name: 'Turkey' },
                { isoCode: 'TM', name: 'Turkmenistan' },
                { isoCode: 'TC', name: 'Turks and Caicos Islands' },
                { isoCode: 'TV', name: 'Tuvalu' },
                { isoCode: 'UG', name: 'Uganda' },
                // BL - { isoCode: 'UA', name: 'Ukraine' },
                { isoCode: 'AE', name: 'United Arab Emirates' },
                { isoCode: 'GB', name: 'United Kingdom' },
                { isoCode: 'US', name: 'United States' },
                { isoCode: 'UM', name: 'United States Minor Outlying Islands' },
                { isoCode: 'UY', name: 'Uruguay' },
                { isoCode: 'UZ', name: 'Uzbekistan' },
                { isoCode: 'VU', name: 'Vanuatu' },
                { isoCode: 'VA', name: 'Vatican' },
                { isoCode: 'VE', name: 'Venezuela' },
                // BL - { isoCode: 'VN', name: 'Vietnam' },
                { isoCode: 'VG', name: 'Virgin Islands, British' },
                { isoCode: 'VI', name: 'Virgin Islands, U.S.' },
                { isoCode: 'WF', name: 'Wallis and Futuna' },
                { isoCode: 'EH', name: 'Western Sahara' },
                { isoCode: 'YE', name: 'Yemen' },
                { isoCode: 'ZM', name: 'Zambia' },
                { isoCode: 'ZW', name: 'Zimbabwe' }
            ];
            return countries;
        }
    }
})();